### PR TITLE
Streamrefactor

### PR DESCRIPTION
**Pull request by EvilFreelancer**
* Implementation of stream based consenption

### CODE REVIEW

**Comment by EvilFreelancer** [comment]
Okay, all seems work on x64 machines, and almost work on x32, probably need to add some "if then else" statement for x32 and just skip part of tests which may be executed only on x64, but how make it with data providers?

**Comment by EvilFreelancer** [comment]
Tests specific for x64 is now will be skipped on x32

**Comment by matracine** [comment]
@EvilFreelancer : "How make it with dataproviders", I supose you are talking about test methods.
Y
ou can construct the return array :
```php
public function dataProvider()
{
  $data = [
// All 32 bits compatibles datas
    [ 0, 0...],
    [0,2...],
....
];
if (PHP_INT_SIZE>4)
{
// All 64 bites comptbles datas
$data[] = [xxx, xxx];
$data[] = [yyyy, yyy];
...
}
return $data;
}
```

**Comment by EvilFreelancer** [comment]
@matracine nice idea, I've added this check to tests

**Pull request merged**
