### PR TITLE
Added blocking socket mode option

### PR DESCRIPTION
**Pull request by majsterkoo**
This commit fix bug with socket timeout after reboot device. #36 

Setting stream to blocking mode, stream was waiting for data to become avaible on the stream for given time (stream_timeout config parameter) and then timed out. So, If we reboot device, stream timed out after stream_timeout and we can continue processing php script (reconnect after reboot need be handle manually by programmer).

In non-blocking mode, socket timeout not working (because non blocking not waiting for data to be available).

In this commit, stream is set to blocking mode defaultly. After some testing on real device, it seems fully working.

When using command which cause device is disconnected (changing wlan parameters on device connected via wlan interface), remember, when using blocking mode, socket timeout must be longer, than time when device is inaccessible. When device is inaccessible longer than is socket timeout, StreamException will be thrown.

Using longer socket timeout means, that script will be longer "waiting" for device be back online. On other hand, using longer socket timeout means, that script will be longer "waiting" for rebooted device (after reboot, socket must be reconnect manually!) or longer timeout before throw StreamException when device died during operation.

I think, this feature should by documented in readme, but I have absolutely no idea how to describe it for "non pro" users. :)
Maybe just documenting socket timeout as value while waiting for response from device (?).

### CODE REVIEW

**Comment by EvilFreelancer** [comment]
Hello @majsterkoo, nice to see you again! Can you please add description to PR?

**Comment by EvilFreelancer** [comment]
Hm, seems you forgot to run tests, i see couple errors with check of amount of parameters in Config object.

**Comment by majsterkoo** [comment]
Hi, I will fix tests and add description later this week.
Thanks for patient.

**Comment by EvilFreelancer** [comment]
Okay, thanks

**Comment by EvilFreelancer** [comment]
@majsterkoo hello! Thanks for update, i have only two suggestion:
1) can you please rename BLOCKING const to SOCKET_BLOCKING? To make it clear what this parameter refers to.
2) Can you please add this parameter with preset default value to Laravel configuration too? I mean `configs/routeros-api.php` file.

> Maybe just documenting socket timeout as value while waiting for response from device (?).
It's a good idea, I will add a description of the problem to the README and how it can be solved through the settings you added.

Thanks a lot for you for your efforts :)

**Comment by EvilFreelancer** [comment]
Everything looks fine, thanks again!

**Pull request merged**
