### PR TITLE
Fixed SSL Connection in newer OpenSSL

### PR DESCRIPTION
**Pull request by k3dt**

### CODE REVIEW

**Comment by EvilFreelancer** [comment]
Hello @k3dt, thanks to your PR! Can you please provide more details in description about your change and which issue this PR should solve?

**Comment by matracine** [comment]
Hello @EvilFreelancer,
The PR allow connexion with poor SSL cipher security level. SECLEVEL=0, allow almost everything with low security CIPHER suite.
You can have a look on this page to see security levels availables : https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

Reading this page, https://wiki.mikrotik.com/wiki/Manual:API-SSL, I thinkk that is necessary when you don't use certificate.
I thnik that if you generate a certificate and bind it to api-ssl service, the SECLEVEL=0 is no more mandatory to connect.
Have to check...

**Comment by EvilFreelancer** [comment]
Hm, then maybe better to add these security levels to settings?

**Comment by k3dt** [comment]
Yes, its neccesary if you dont use certificate. Because of verify_peer = false i think its not neccesary add this to settings.

**Comment by EvilFreelancer** [comment]
Okay, it will be added as configurable parameter in 1.3.1, hope today i will have time :)

**Comment by EvilFreelancer** [comment]
Hello!

`ssl_options` parameter added to config, you can configure any settings described in [SSL context options](https://www.php.net/manual/en/context.ssl.php) documentation.

This feature is available in 1.3.1 version of library.

Some additional details available in [comments of source code](https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Config.php#L46).

Simple usage example:
```php
$client = new Client([
    'timeout'     => 1,
    'host'        => '127.0.0.1',
    'user'        => 'admin',
    'pass'        => 'admin',
    'ssl'         => true,
    'ssl_options' => [
        'ciphers'           => 'ADH:ALL', // ADH:ALL, ADH:ALL@SECLEVEL=0, ADH:ALL@SECLEVEL=1 ...
        'verify_peer'       => true,      // Require verification of SSL certificate used.
        'verify_peer_name'  => false,     // Require verification of peer name.
        'allow_self_signed' => true,      // Allow self-signed certificates. Requires verify_peer.
    ],
]);
```

I cancel this pull request, because necessary logic was implemented differently.

**Pull request closed without merging**
